language: python

sudo: false

env:
  - TOXENV=flake8
  - TOXENV=py34-dj17-cms31
  - TOXENV=py34-dj17-cms30
  - TOXENV=py34-dj16-cms31
  - TOXENV=py34-dj16-cms30
  - TOXENV=py33-dj17-cms31
  - TOXENV=py33-dj17-cms30
  - TOXENV=py33-dj16-cms31
  - TOXENV=py33-dj16-cms30
  - TOXENV=py27-dj17-cms31
  - TOXENV=py27-dj17-cms30
  - TOXENV=py27-dj16-cms31
  - TOXENV=py27-dj16-cms30

install:
  - pip install tox coveralls

script:
  - tox -e $TOXENV

after_success:
  - coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
